# Generated by Django 3.1.2 on 2022-02-08 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=100, verbose_name='ShopName')),
                ('text', models.TextField(verbose_name='Text')),
                ('logo_shop', models.ImageField(blank=True, upload_to='media/shop_image')),
                ('website', models.CharField(max_length=100, verbose_name='Website')),
                ('slug', models.SlugField(default=models.CharField(max_length=100, verbose_name='ShopName'))),
            ],
        ),
    ]
